version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hema_ratings
      POSTGRES_USER: hema_user
      POSTGRES_PASSWORD: hema_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./src/hemanalyzer/hema_ratings:/data:ro
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://hema_user:hema_password@db:5432/hema_ratings
    volumes:
      - ./src:/app/src
    command: ["poetry", "run", "hemanalyzer"]

volumes:
  postgres_data: